In [2]:
import cuvs
cuvs.__version__

'25.02.00'

In [3]:
import numpy as  np
import cupy as  cp
from cuvs.neighbors import cagra

# 데이터셋 생성 및 GPU로 이동
data  =  cp.random.random((10000, 128), dtype=cp.float32) # 10,000개의 128차원 벡터

# CAGRA 인덱스 파라미터 설정
index_params  = cagra.IndexParams(
metric='sqeuclidean', # 거리 측정 방식: 제곱 유클리드 거리
intermediate_graph_degree=128,
graph_degree=64,
build_algo='ivf_pq'  # 그래프 구축 알고리즘: IVF-PQ
)

# CAGRA 인덱스 생성 및 구축
index  = cagra.build(index_params, data)

# 쿼리 벡터 생성 및 GPU로 이동
queries  =  cp.random.random((5, 128), dtype=cp.float32) # 5개의 128차원 쿼리 벡터

# 검색 파라미터 설정
search_params  = cagra.SearchParams()

# 검색 수행
k  =  10  # 상위 10개의 근접 이웃 검색
distances, neighbors  = cagra.search(index=index, queries=queries, k=k, search_params=search_params)

# 결과 출력 (GPU 메모리에서 CPU 메모리로 복사)
print("이웃 인덱스:\n", cp.asnumpy(neighbors))
print("거리:\n", cp.asnumpy(distances))


[2025-03-01 13:20:02.662] [RAFT] [info] optimizing graph
[2025-03-01 13:20:02.712] [RAFT] [info] Graph optimized, creating index


using ivf_pq::index_params nrows 10000, dim 128, n_lists 100, pq_dim 32
이웃 인덱스:
 [[7320 8244  364 7682  306 7730 7650 4079 8983 8748]
 [ 439 2716 4913  352 2679 8881 6269  452  998 4694]
 [6016 9406   46 1944 2802 2721 4530 3532 2426 9364]
 [4560 5038 7544 7555 4052 6916 6361 7831 9444 5613]
 [5705 1789 2992 4292 7557 9772 2976 2418 4665 8348]]
거리:
 [[13.464382  13.759015  14.128194  14.329628  14.501444  14.822922
  14.835612  14.839935  14.98467   15.028872 ]
 [12.945017  14.685237  14.741364  14.885988  14.910499  14.935569
  15.0006895 15.164157  15.186855  15.213362 ]
 [13.82794   13.888212  14.296035  14.844983  14.949133  15.07353
  15.1515665 15.186882  15.207842  15.313015 ]
 [13.733449  14.198616  14.31017   14.385824  14.532615  14.626123
  15.010791  15.078496  15.1200285 15.135775 ]
 [13.176027  13.415209  14.147243  14.332291  14.601057  14.650551
  14.716481  14.871971  14.895951  14.975443 ]]
