# Import CuPy and Numpy

In [1]:
import numpy as np
import cupy as cp

# CuPy Custom Kernels

In [2]:
x = cp.arange(6, dtype='f').reshape(2, 3)
y = cp.arange(3, dtype='f')

In [3]:
x

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [4]:
y

array([0., 1., 2.], dtype=float32)

In [5]:
kernel = cp.ElementwiseKernel(
    'float32 x, float32 y', 'float32 z',
    '''
    if (x -2 > y) {
        z = x * y;
    } else {
        z = x + y;
    }
    ''', 'my_kernel'
)

In [6]:
kernel(x, y)

array([[ 0.,  2.,  4.],
       [ 0.,  4., 10.]], dtype=float32)

# 쉽게 작성을 도와주는 FUSE

In [7]:
@cp.fuse(kernel_name='my_kernel')
def elementwise_mykernel(x, y):
    return cp.where(x-2 > y, x * y, x + y) 


In [8]:
elementwise_mykernel(x, y)

array([[ 0.,  2.,  4.],
       [ 0.,  4., 10.]], dtype=float32)